# -*- coding: utf-8 -*-
"""CODING_SAMURAI(PREDICTING TIME SERIES)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RIrl_4fv7alZxsr7QLTLkFpKHmKJmmx5
"""

import pandas as pd
df=pd.read_csv(r"C:\Users\PC\Downloads\SuperStoreOrders - SuperStoreOrders.csv")
df.head()

import pandas as pd
from google.colab import files
uploaded = files.upload()

df = pd.read_csv("SuperStoreOrders - SuperStoreOrders.csv", parse_dates=['order_date'],index_col= ['order_date'], dayfirst=True)
df.head()

# extract year_month from order_date
df['year_month']= df.index.strftime('%Y-%m')
df['year_month']

# extract year from order_date
df['year']=df.index.strftime('%Y')
df['year']

df.loc[pd.Timestamp('2013-01-01'):pd.Timestamp('2014-12-31')]

import matplotlib.pyplot as plt

# Group by year and sum the quantity
yearly_quantity = df.groupby('year_month')['quantity'].sum()

# Plot the aggregated data
yearly_quantity.plot(kind='line')

plt.xlabel('Year_month')
plt.ylabel('Total Quantity')
plt.title('Total Quantity per Year')
plt.show()

# trend of yearly_monthly for profit

import matplotlib.pyplot as plt

yearly_profit = df.groupby('year_month')['profit'].mean()
yearly_profit

yearly_profit.plot(kind='line')
plt.xlabel('year_month')
plt.ylabel('yearly_profit')
plt.title('yearly_profit_trend')
plt.show()

# expanding chart # identitfy the trend - is the seasonal constant or not ?
#from pylab import rcParams
#rcParams['figure.figsize'] = 15, 10
#df.plot()
#plt.show()

# Convert 'sales' column to numeric, handling commas and potential errors
df['sales'] = df['sales'].astype(str).str.replace(',', '', regex=False).astype(float)

# Get Unique brand names from the category col
unique_brands_list = df['category'].unique().tolist()
print(unique_brands_list)

# yearly sales brand wise
brand_yearly_sales = df.groupby(['year_month', 'category'])['sales'].sum().reset_index()
brand_yearly_sales

# plt a line chart showcasing yearly sales per category

import matplotlib.pyplot as plt

brand_yearly_sales.plot(kind='line')
plt_xlable="yearly_sales"
plt_ylabel="catgeory"
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose
from pylab import rcParams

rcParams['figure.figsize'] = 15, 10 # Increase figure size for better visibility
df_add_decompose=seasonal_decompose(df['sales'],model='additive',period=12)
df_add_decompose.plot()
plt.show()

# Resample sales data to monthly frequency, summing up sales for each month
monthly_sales = df['sales'].resample('MS').sum()

# Display the first few entries of the monthly sales data
display(monthly_sales.head())

"""Now that we have monthly sales data, we can apply seasonal decomposition with a period of 12 to observe the annual seasonal pattern more accurately."""

import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose
from pylab import rcParams

rcParams['figure.figsize'] = 15, 10 # Increase figure size for better visibility

# Perform additive seasonal decomposition on monthly sales with period=12
df_monthly_decompose = seasonal_decompose(monthly_sales, model='additive', period=12)
df_monthly_decompose.plot()
plt.title('Monthly Sales Additive Seasonal Decomposition (Period=12)')
plt.show()

# decompose the timeseries multipilcation