# -*- coding: utf-8 -*-
"""CODING_SAMURAI_PROJ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_Ur-Uwrw8qJhE34pXSIVfCSd2OxzDcv
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_excel('QVI_transaction_data (1).xlsx')
df.head()
df.info()
df.describe()
df.isnull().sum()

import pandas as pd
df = pd.read_csv('QVI_purchase_behaviour (1).csv')
df.head()
df.info()
df.describe()
df.isnull().sum()

# finding Null values table 1
import pandas as pd

df = pd.read_excel('QVI_transaction_data (1).xlsx')
df.isnull().sum()

# finding Null values Table 2
import pandas as pd
df = pd.read_csv('QVI_purchase_behaviour (1).csv')
df.isnull().sum()

# finding duplicates table 1
import pandas as pd

df = pd.read_excel('QVI_transaction_data (1).xlsx')

df.duplicated().sum()
# removing duplicates
df.dropna(inplace=True)
# checking again total count of duplicates
df.duplicated().sum()
# fiding duplicate rows
df[df.duplicated()]
# removing duplicate rows
df.drop_duplicates(inplace=True)
# again checking if any duplicate rows
df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist())

# checking data types
df.dtypes
df
df['DATE'] = pd.to_datetime(df['DATE'], origin='1899-12-30', unit='D')
df

# finding duplicates table 2

import pandas as pd
df = pd.read_csv('QVI_purchase_behaviour (1).csv')
df.duplicated().sum()
# chechking data types
df.dtypes
# chnaging col name LYLTY_CARD_NBR = Loyalty_card_Nbr
df.rename(columns={'LYLTY_CARD_NBR': 'LOYALTY_CARD_NBR'}, inplace=True)
df.columns.tolist()
df

# Finding Outliers for col. TOT_SALES
import pandas as pd

df = pd.read_excel('QVI_transaction_data (1).xlsx')
df

# calculating Q3 and Q1
Q1 = df['TOT_SALES'].quantile(0.25)
Q3 = df['TOT_SALES'].quantile(0.75)
print(Q1,Q3)

# FINDING IQR
IQR = Q3 - Q1
print(IQR)

# Finding Upper & Lower limit
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR
print(lower_limit,upper_limit)

outliers = df[(df['TOT_SALES'] < lower_limit) | (df['TOT_SALES'] > upper_limit)]

outliers

# EDA Analysis
df = pd.read_excel('QVI_transaction_data (1).xlsx')
df.head(100)

#chip/chps replaced by chips
df['PROD_NAME'] = df['PROD_NAME'].str.replace(r'\b(chip|chps|chips|ChipCo|Chp)\b', 'Chips', regex=True, case=False)
# replacing ChpsHny wiith Chips & honey
df['PROD_NAME'] = df['PROD_NAME'].str.replace('ChpsHny', 'Chips and Honey', regex=True, case=False)

# finding non chips products
df.loc[~df['PROD_NAME'].str.contains('Chips', case=False, na=False), 'PROD_NAME'].unique()
df

print(non_chips)

# finding occurence of PROD_NAME

prod_count = (
    df.groupby('PROD_NAME')
      .size()
      .reset_index(name='Count')
      .sort_values(by='Count', ascending=False)
)

prod_count

# describe data MEAN,MEDIAN,MAX,MIN.Q1,

df = pd.read_excel('QVI_transaction_data (1).xlsx')
df.describe()

# DATE WISE TRANSACTIONS

df['DATE'] = pd.to_datetime(df['DATE'], origin='1899-12-30', unit='D')

date_wise_txn = (
    df.groupby('DATE')['TXN_ID']
      .count()
      .reset_index(name='Total_Transactions')
      .sort_values('DATE')
)

date_wise_txn

import matplotlib.pyplot as plt

plt.figure()
plt.plot(date_wise_txn['DATE'], date_wise_txn['Total_Transactions'])

plt.xlabel('Date')
plt.ylabel('Total Transactions')
plt.title('Date-wise Transactions')

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# can we make it better ?

from google.colab import files
uploaded = files.upload()

# Monthly sales trend analysis
import pandas as pd

df = pd.read_excel('QVI_transaction_data (1).xlsx')
df['DATE'] = pd.to_datetime(df['DATE'], origin='1899-12-30', unit='D')

Month = df['Month'] = df['DATE'].dt.month_name()

monthly_txn = (
    df.groupby('Month')['TXN_ID']
      .count()
      .reset_index(name='Total_Transactions')
)

# Define the desired chronological order of months
month_order = ['January', 'February', 'March', 'April', 'May', 'June',
               'July', 'August', 'September', 'October', 'November', 'December']

# Convert the 'Month' column to a categorical type with the specified order
monthly_txn['Month'] = pd.Categorical(monthly_txn['Month'], categories=month_order, ordered=True)

# Sort the DataFrame by the new categorical 'Month' column
monthly_txn = monthly_txn.sort_values('Month')
monthly_txn

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(monthly_txn['Month'], monthly_txn['Total_Transactions'], marker='o', linestyle='-', color='skyblue', label='Monthly Transactions')

# Highlight highest month
highest_month_data = monthly_txn.loc[monthly_txn['Total_Transactions'].idxmax()]
plt.plot(highest_month_data['Month'], highest_month_data['Total_Transactions'], marker='o', markersize=10, color='green', label='Highest Month')
plt.annotate(f"{highest_month_data['Month']}: {highest_month_data['Total_Transactions']}",
             (highest_month_data['Month'], highest_month_data['Total_Transactions']),
             textcoords="offset points", xytext=(0,10), ha='center', color='green', fontweight='bold')

# Highlight lowest month
lowest_month_data = monthly_txn.loc[monthly_txn['Total_Transactions'].idxmin()]
plt.plot(lowest_month_data['Month'], lowest_month_data['Total_Transactions'], marker='o', markersize=10, color='red', label='Lowest Month')
plt.annotate(f"{lowest_month_data['Month']}: {lowest_month_data['Total_Transactions']}",
             (lowest_month_data['Month'], lowest_month_data['Total_Transactions']),
             textcoords="offset points", xytext=(0,-15), ha='center', color='red', fontweight='bold')

plt.xlabel('Month')
plt.ylabel('Total Transactions')
plt.title('Month-wise Transactions with Highlighted Highest and Lowest Months')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Transactions per region

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('QVI_transaction_data (1).xlsx')
df.columns.tolist()

import re

# Extract numerical values (pack size) from PROD_NAME using regex and convert to Int64
df['PACK_SIZE'] = df['PROD_NAME'].str.extract('(\\d+)[Gg]').astype('Int64')

# Display unique values and their counts for the new PACK_SIZE column
print(df['PACK_SIZE'].value_counts().sort_index())

# Display the data type of the new PACK_SIZE column
print(df['PACK_SIZE'].dtype)

import matplotlib.pyplot as plt
import re
import pandas as pd

# Reload df and re-extract PACK_SIZE to ensure it's available
# Assuming df is intended to be loaded from 'QVI_transaction_data (1).xlsx' for this analysis
df = pd.read_excel('QVI_transaction_data (1).xlsx')

# Extract numerical values (pack size) from PROD_NAME using regex and convert to Int64
df['PACK_SIZE'] = df['PROD_NAME'].str.extract('(\\d+)[Gg]').astype('Int64')

plt.figure(figsize=(12, 6))
df['PACK_SIZE'].value_counts().sort_index().plot(kind='bar')
plt.xlabel('Pack Size (grams)')
plt.ylabel('Number of Transactions')
plt.title('Distribution of Product Pack Sizes')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Extracting brand names
df['BRAND']= df['PROD_NAME'].str.extract(r'([A-Za-z]+)')

# Correcting Brand Names
df['BRAND'] = df['BRAND'].replace({
    'Red': 'RRD',
    'Snbts': 'Sunbites',
    'Infzns': 'Infuzions',
    'WW': 'Woolworths',
    'Smith': 'Smiths',
    'Ncc': 'Natural',
    'Dorito': 'Doritos',
    'Grain': 'GrnWves',
    'Tostitos': 'Doritos'
})
df.BRAND.unique().tolist()


# brand wise transactions
Salex =df.groupby('BRAND')['TXN_ID'].count().sort_values(ascending=False)
Salex

import matplotlib.pyplot as plt

plt.figure(figsize=(15, 7))
Salex.plot(kind='bar')
plt.title('Total Transactions by Brand')
plt.xlabel('Brand')
plt.ylabel('Number of Transactions')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

df= pd.read_csv('QVI_purchase_behaviour (1).csv')
df.head(50)

# Lifestage wise premium customers
Txn_age = df.groupby('LIFESTAGE')['PREMIUM_CUSTOMER'].count().sort_values(ascending=False)
Txn_age

# Ct. of customer per purchase amount category
Purchase_behv =df.groupby('PREMIUM_CUSTOMER')['PREMIUM_CUSTOMER'].count().sort_values(ascending=False)
Purchase_behv

import pandas as pd

# --- Prepare Transaction Data --- #
# Load transaction data from the original Excel file
transactions_df = pd.read_excel('QVI_transaction_data (1).xlsx')

# Convert DATE column to datetime
transactions_df['DATE'] = pd.to_datetime(transactions_df['DATE'], origin='1899-12-30', unit='D')

# Clean PROD_NAME column (replace variations of 'chip' with 'Chips' and 'ChpsHny' with 'Chips and Honey')
transactions_df['PROD_NAME'] = transactions_df['PROD_NAME'].str.replace(r'\b(chip|chps|chips|ChipCo|Chp)\b', 'Chips', regex=True, case=False)
transactions_df['PROD_NAME'] = transactions_df['PROD_NAME'].str.replace('ChpsHny', 'Chips and Honey', regex=True, case=False)

# Extract and correct Brand names
transactions_df['BRAND'] = transactions_df['PROD_NAME'].str.extract(r'([A-Za-z]+)')
transactions_df['BRAND'] = transactions_df['BRAND'].replace({
    'Red': 'RRD',
    'Snbts': 'Sunbites',
    'Infzns': 'Infuzions',
    'WW': 'Woolworths',
    'Smith': 'Smiths',
    'Ncc': 'Natural',
    'Dorito': 'Doritos',
    'Grain': 'GrnWves'
})

# --- Prepare Customer Data --- #
# Load customer purchase behaviour data
customer_df = pd.read_csv('QVI_purchase_behaviour (1).csv')

# Rename LYLTY_CARD_NBR column for consistency with transactions_df if needed for merge, or keep original if transactions_df has a similar column
# For this merge, both tables should have a common key. Let's assume the transaction data's 'LYLTY_CARD_NBR' is the same as customer_df's.
# If customer_df was already renamed to 'LOYALTY_CARD_NBR', then we just need to ensure consistency.
customer_df.rename(columns={'LYLTY_CARD_NBR': 'LOYALTY_CARD_NBR'}, inplace=True)

# --- Merge the DataFrames --- #
# Merge transaction data with customer purchase behaviour data on the loyalty card number
merged_df = pd.merge(transactions_df, customer_df, left_on='LYLTY_CARD_NBR', right_on='LOYALTY_CARD_NBR', how='left')

# Display the head of the merged DataFrame and its info to verify the merge
display(merged_df.head())
display(merged_df.info())

# ct of duplicates
df.duplicated().sum()
#ct of null values
df.isnull().sum()
# null values in LIFESTAGE
df['LIFESTAGE'].isnull().sum()

# proportion of sales per customer segments and based on purchasing behaviour
SALES = merged_df.groupby(['LIFESTAGE', 'PREMIUM_CUSTOMER'])['TOT_SALES'].sum().sort_values(ascending=False)
SALES

import matplotlib.pyplot as plt

# Unstack the SALES Series to prepare for plotting stacked area chart
sales_unstacked = SALES.unstack(level='PREMIUM_CUSTOMER')

# Plot a stacked area chart
sales_unstacked.plot(kind='bar', stacked=True, figsize=(12, 7))
plt.title('Total Sales per Customer Segment by Premium Customer Status')
plt.xlabel('Lifestage')
plt.ylabel('Total Sales')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Premium Customer')
plt.tight_layout()
plt.show()

# proportion of Customers per customer segments and based on purchasing behaviour
CUST = merged_df.groupby(['LIFESTAGE', 'PREMIUM_CUSTOMER'])['PREMIUM_CUSTOMER'].count().sort_values(ascending=False)
CUST

import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('QVI_purchase_behaviour (1).csv')

customer_df = pd.read_csv('QVI_purchase_behaviour (1).csv')
transactions_df = pd.read_excel('QVI_transaction_data (1).xlsx')

# Rename the column in customer_df to match the merge key
customer_df.rename(columns={'LYLTY_CARD_NBR': 'LOYALTY_CARD_NBR'}, inplace=True)

merged_df = pd.merge(transactions_df, customer_df, left_on='LYLTY_CARD_NBR', right_on='LOYALTY_CARD_NBR', how='left')

# proportion of Customers per customer segments and based on purchasing behaviour
CUST = merged_df.groupby(['LIFESTAGE', 'PREMIUM_CUSTOMER'])['PREMIUM_CUSTOMER'].count().sort_values(ascending=False)

# Unstack the Customer Series to prepare for plotting stacked area chart
CUST_unstacked = CUST.unstack(level='PREMIUM_CUSTOMER')

# Plot a stacked area chart
ax = CUST_unstacked.plot(kind='bar', stacked=True, figsize=(15, 8))
plt.title('Total customers per Customer Segment by Premium Customer Status')
plt.xlabel('Lifestage')
plt.ylabel('Total Customers')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Premium Customer')

# Add data labels
for container in ax.containers:
    labels = [v.get_height() if v.get_height() > 0 else '' for v in container]
    ax.bar_label(container, labels=labels, fmt='%g', label_type='center')

plt.tight_layout()
plt.show()

# Total units per customer segment and Premium Customers

QTY = merged_df.groupby(['LIFESTAGE', 'PREMIUM_CUSTOMER'])['PROD_QTY'].sum().sort_values(ascending=False)
QTY

import matplotlib.pyplot as plt

# Total Qty per customer segments and based on purchasing behaviour
QTY = merged_df.groupby(['LIFESTAGE', 'PREMIUM_CUSTOMER'])['PROD_QTY'].sum()

QTY_unstacked = QTY.unstack(level='PREMIUM_CUSTOMER')

# GROUPED bar chart (separate column for each legend category)
ax = QTY_unstacked.plot(kind='bar', stacked=False, figsize=(15, 8))

plt.title('Total Quantity per Customer Segment by Premium Customer Status')
plt.xlabel('Lifestage')
plt.ylabel('Total Quantity Sold')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Premium Customer')

plt.tight_layout()
plt.show()

# Avg price per Customer segment and Premium Customer TYPE
#### Average price per customer by LIFESTAGE and PREMIUM_CUSTOMER

# Average price per customer by LIFESTAGE and PREMIUM_CUSTOMER

avg_price = (
    merged_df
    .groupby(['LIFESTAGE','PREMIUM_CUSTOMER','LYLTY_CARD_NBR'])['TOT_SALES']
    .sum()                                   # total price per customer
    .groupby(['LIFESTAGE','PREMIUM_CUSTOMER'])
    .mean()                                  # average per customer
    .reset_index(name='AVG_PRICE_PER_CUSTOMER')
)

avg_price

# Avg units per customer
import matplotlib.pyplot as plt

avg_units = (
    merged_df
    .groupby(['LIFESTAGE', 'PREMIUM_CUSTOMER', 'LYLTY_CARD_NBR'])['PROD_QTY']
    .sum() # total quantity per customer
    .groupby(['LIFESTAGE', 'PREMIUM_CUSTOMER'])
    .mean() # average per customer
    .reset_index(name='AVG_UNITS_PER_CUSTOMER')
)

# Pivot for plotting
avg_units_pivot = avg_units.pivot(index='LIFESTAGE', columns='PREMIUM_CUSTOMER', values='AVG_UNITS_PER_CUSTOMER')

# Plot grouped bar chart
ax = avg_units_pivot.plot(kind='bar', stacked=False, figsize=(15, 8)) # Changed stacked to False

plt.title('Average Units per Customer by Lifestage and Premium Customer Status')
plt.xlabel('Lifestage')
plt.ylabel('Average Units per Customer')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Premium Customer')

plt.tight_layout()
plt.show()

# Price per unit
import matplotlib.pyplot as plt

# Calculate price per unit for each transaction
merged_df['PRICE_PER_UNIT'] = merged_df['TOT_SALES'] / merged_df['PROD_QTY']

# Calculate average price per unit per customer, grouped by LIFESTAGE and PREMIUM_CUSTOMER
avg_price_per_unit = (
    merged_df
    .groupby(['LIFESTAGE', 'PREMIUM_CUSTOMER', 'LYLTY_CARD_NBR'])['PRICE_PER_UNIT']
    .mean() # average price per unit per customer
    .groupby(['LIFESTAGE', 'PREMIUM_CUSTOMER'])
    .mean() # average price per unit across customers in each segment
    .reset_index(name='AVG_PRICE_PER_UNIT')
)

# Pivot for plotting
avg_price_per_unit_pivot = avg_price_per_unit.pivot(index='LIFESTAGE', columns='PREMIUM_CUSTOMER', values='AVG_PRICE_PER_UNIT')

# Plot grouped bar chart
ax = avg_price_per_unit_pivot.plot(kind='bar', stacked=False, figsize=(15, 8))

plt.title('Average Price Per Unit by Lifestage and Premium Customer Status')
plt.xlabel('Lifestage')
plt.ylabel('Average Price Per Unit')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Premium Customer')

plt.tight_layout()
plt.show()

# Predicting Forecast analysis

# Monthly sales aggregation for trend analysis
merged_df['DATE'] = pd.to_datetime(merged_df['DATE'], origin='1899-12-30', unit='D', errors='coerce')
monthly_sales = merged_df.set_index('DATE')['TOT_SALES'].resample('ME').sum()

# Display the monthly sales data
print("Monthly Sales Data:")
print(monthly_sales.head())
print(monthly_sales.tail())

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(monthly_sales.index, monthly_sales.values, marker='o', linestyle='-', color='skyblue')
plt.xlabel('Date')
plt.ylabel('Total Sales')
plt.title('Monthly Sales Trend')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""# Task
* **Prepare Monthly Transaction Data**: Aggregate the transaction data from 'merged_df' on a monthly basis to get the total transaction count for each month. This will serve as the time series data for forecasting.
* **Build and Forecast Transactions**: Utilize a time series forecasting model (e.g., Exponential Smoothing) on the monthly transaction data to predict transaction counts for the months following the last historical data point (July 2019 onwards).
* **Visualize Historical and Forecasted Transactions**: Plot the historical monthly transaction data as a solid line and overlay the forecasted transaction data as a dotted line on the same chart, ensuring clear labels and a title.
* **Final Task**: Provide insights into the forecasted transaction trend and any observations from the visualization.

## Prepare Monthly Transaction Data

### Subtask:
Aggregate the transaction data from 'merged_df' on a monthly basis to get the total transaction count for each month. This will serve as the time series data for forecasting.

**Reasoning**:
The subtask requires aggregating transaction data on a monthly basis by counting the number of transactions. I will use `resample('MS')` on the `DATE` column after setting it as the index, and then count the `TXN_ID` to get monthly transaction counts. The `DATE` column is already in datetime format in `merged_df` from previous steps.

**Reasoning**:
The error occurred because the 'DATE' column in `merged_df` was already in datetime format, and applying `pd.to_datetime` with `origin` and `unit` parameters to an already datetime column is incorrect. I will remove the unnecessary `pd.to_datetime` conversion and proceed directly to resampling.
"""

import pandas as pd

# Ensure the 'DATE' column is in datetime format (it was already converted in a previous step, so this line is simplified)
# No need to use origin and unit if the column is already datetime
# merged_df['DATE'] = pd.to_datetime(merged_df['DATE'], errors='coerce') # This line is not strictly needed if merged_df['DATE'] is already datetime

# Aggregate merged_df by month to count the number of transactions (TXN_ID)
monthly_transactions = merged_df.set_index('DATE')['TXN_ID'].resample('MS').count()

# Display the monthly transaction data
print("Monthly Transaction Count:")
print(monthly_transactions.head())
print(monthly_transactions.tail())

"""**Reasoning**:
The subtask requires building and forecasting transactions using a time series model. I will use the Exponential Smoothing model from `statsmodels.tsa.holtwinters` as suggested by the main task to forecast future monthly transactions.


"""

from statsmodels.tsa.holtwinters import ExponentialSmoothing

# Define the number of future periods to forecast
n_forecast_periods = 6

# Build and fit the Exponential Smoothing model
# Using a simple additive model since there isn't clear seasonality mentioned yet
# And assuming a trend based on the initial monthly sales plot.
# 'add' for additive trend, 'mul' for multiplicative trend
# 'seasonal_periods' can be set if seasonality is observed, e.g., 12 for yearly seasonality.
model = ExponentialSmoothing(monthly_transactions, trend='add', seasonal=None, seasonal_periods=None)
fit_model = model.fit()

# Forecast future transactions
forecast = fit_model.forecast(n_forecast_periods)

# Display the forecasted monthly transactions
print("Forecasted Monthly Transactions (next 6 months):")
print(forecast)

"""**Reasoning**:
The subtask requires visualizing the historical and forecasted transactions. I will plot `monthly_transactions` (historical data) as a solid line and `forecast` (forecasted data) as a dotted line on the same chart to compare their trends.


"""

import matplotlib.pyplot as plt

# Create a figure and an axes object
plt.figure(figsize=(12, 6))

# Plot historical data
plt.plot(monthly_transactions.index, monthly_transactions.values, label='Historical Transactions', color='blue', linestyle='-')

# Plot forecasted data
plt.plot(forecast.index, forecast.values, label='Forecasted Transactions', color='red', linestyle='--')

# Add labels and title
plt.xlabel('Date')
plt.ylabel('Total Transactions')
plt.title('Historical and Forecasted Monthly Transactions')

# Add legend and grid
plt.legend()
plt.grid(True)

# Rotate x-axis labels for better readability
plt.xticks(rotation=45)

# Adjust layout to prevent labels from overlapping
plt.tight_layout()

# Display the plot
plt.show()

"""## Final Task

### Subtask:
Provide insights into the forecasted transaction trend and any observations from the visualization.

## Summary:

### Q&A
The forecasted transaction trend indicates a slight, gradual downward trend over the next six months (July to December 2019), with transaction counts decreasing from approximately 21,800 to 21,600. Historically, transaction data shows month-to-month variability but generally hovers around 21,000-22,000 transactions, without a strong overall increasing or decreasing trend, suggesting relative stability. The current Exponential Smoothing model, without explicit seasonality, captures the general average level but may not fully account for historical monthly fluctuations.

### Data Analysis Key Findings
*   **Monthly Transaction Aggregation**: Historical transaction data was successfully aggregated monthly, spanning from July 2018 to June 2019. The monthly transaction counts ranged from 22,562 in July 2018 to 21,829 in June 2019.
*   **Historical Trend**: The historical data exhibited general stability around 21,000-22,000 transactions, with some monthly variability (e.g., a dip in February 2019 and peaks in December 2018 and March 2019), but no strong overall increasing or decreasing trend was observed.
*   **Forecasted Trend**: Using an Exponential Smoothing model with an additive trend, the forecast for the next six months (July to December 2019) predicts a slight downward trend. Forecasted transactions start at approximately 21,806.75 in July 2019 and gradually decrease to about 21,604.51 by December 2019.
*   **Model Observation**: The model captured the general average transaction level but, due to the lack of explicit seasonality, did not account for observed historical monthly fluctuations. The slight downward forecast suggests the model identified a minor negative slope in recent historical data.

### Insights or Next Steps
*   To improve the accuracy of future forecasts, incorporate seasonality into the Exponential Smoothing model (e.g., `seasonal='add'` and `seasonal_periods=12`) to better capture recurring monthly patterns observed in historical data.
*   Analyze the reasons behind the slight downward trend projected by the model and the historical fluctuations (e.g., February dip, December/March peaks) to understand underlying business factors influencing transaction volumes.
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_excel('QVI_transaction_data (1).xlsx')
df.head()

# coverting date (numeric) into date type
df["DATE"] = pd.to_datetime(df["DATE"], origin="1899-12-30", unit="D")

# EXTRACTING MONTH FROM DATE

df['month']=df['DATE'].dt.month
df['year']=df['DATE'].dt.year
df.head()

from sklearn.linear_model import LinearRegression
import numpy as np

monthly_sales = df.groupby('month')['TOT_SALES'].sum().reset_index()

X = np.arange(len(monthly_sales)).reshape(-1,1)
y = monthly_sales['TOT_SALES']

model = LinearRegression()
model.fit(X,y)

next_month = model.predict([[len(monthly_sales)]])
print("Predicted Next Month Sales:", next_month)

# Monthly sales
import pandas as pd

monthly_sales = df.groupby('month')["TOT_SALES"].sum()
monthly_sales

import matplotlib.pyplot as plt

monthly_sales.plot()
plt.title("Monthly Sales Trend")
plt.xlabel("Date")
plt.ylabel("Total Sales")
plt.show()